# Generated by Django 5.0.3 on 2024-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_System_Users',
            fields=[
                ('medical_syster_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_system_user_name', models.CharField(max_length=30)),
                ('medical_system_email', models.EmailField(max_length=254, unique=True)),
                ('medical_system_password', models.CharField(max_length=30)),
                ('medical_system_user_type', models.CharField(max_length=30)),
            ],
        ),
    ]
