# Generated by Django 5.0.3 on 2024-07-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_medical_system_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_system_users',
            name='upload_profile_picture',
            field=models.ImageField(default=True, upload_to='profile_picture_hospital_user'),
        ),
    ]
